/******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/
 
const bGround = require('fcc-express-bground');
const myApp = require('./myApp');
const express = require('express');
const app = express();

if (!process.env.DISABLE_XORIGIN) {
  app.use((req, res, next) => {
    const allowedOrigins = ['https://narrow-plane.gomix.me', 'https://www.freecodecamp.com'];
    const origin = req.headers.origin || '*';
    if(!process.env.XORIG_RESTRICT || allowedOrigins.indexOf(origin) > -1){
         console.log(origin);
         res.setHeader('Access-Control-Allow-Origin', origin);
         res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    }
    next();
  });
}
app.get("/", (req, res)=>{
  console.log("Route / was hit!"); // Add this line
  const relativePath = '/views/index.html'; // Replace with your *relative* path
  //const absolutePath = path.resolve(__dirname, relativePath); // Construct the absolute path//__dirname + relativePath
     const absolutePath = __dirname +'/views/index.html'
  /*if (!absolutePath.startsWith(path.resolve(__dirname))) {
    console.error('Security Violation: Attempted to access a file outside the allowed directory.');
    return res.status(403).send('Forbidden'); // Or another appropriate error response
  }*/
  //res.send(absolutePath);
    res.sendFile(absolutePath, (err) => {
    if (err) {
      console.error("Error sending file:", err);
      res.status(err.status || 500).send('Internal Server Error');
    } else {
      console.log('File sent successfully!');
    }
  });
});

const port = process.env.PORT || 3000;
bGround.setupBackgroundApp(app, myApp, __dirname).listen(port, () => {
  bGround.log(`Node is listening on port ${port}...`);
});



/******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

