/******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/
require('dotenv').config()
const bGround = require("fcc-express-bground");
const myApp = require("./myApp");
const express = require("express");
//const path = require("path"); // 1. 引入 path 模块
const app = express();

if (!process.env.DISABLE_XORIGIN) {
  app.use((req, res, next) => {
    const allowedOrigins = [
      "https://narrow-plane.gomix.me",
      "https://www.freecodecamp.com",
    ];
    const origin = req.headers.origin || "*";
    if (!process.env.XORIG_RESTRICT || allowedOrigins.indexOf(origin) > -1) {
      console.log(origin);
      res.setHeader("Access-Control-Allow-Origin", origin);
      res.header(
        "Access-Control-Allow-Headers",
        "Origin, X-Requested-With, Content-Type, Accept",
      );
    }
    next();
  });
}
/*app.get("/", (req, res)=>{
  console.log('Request URL:', req.url);
  // 使用 path.join 来构建路径更安全和跨平台
  const absolutePath = path.join(__dirname, 'views', 'index.html');

    res.sendFile(absolutePath, (err) => {
    if (err) {
      console.error("Error sending file:", err);
      // 确保在发生错误时发送状态码
      res.status(err.status || 500).send('Internal Server Error');
    } else {
      console.log('File sent successfully!');
    }
  });
});*/
app.use(function middleware(req, res, next) {
  // Do something
  var logStr = req.method + " " + req.path + " - " + req.ip;
  console.log(logStr);
  // Call the next function in line:
  next();
});
app.use("/public", express.static(__dirname + "/public"));
app.get("/json", (req, res) => {
  //res.sendFile(__dirname + "/views/index.html");
  if(process.env.MESSAGE_STYLE=='uppercase'){
    res.json({"message": "HELLO JSON"})
  }else{
    res.json({"message": "Hello json"})
  }

});

const port = process.env.PORT || 3000;
bGround.setupBackgroundApp(app, myApp, __dirname).listen(port, () => {
  bGround.log(`Node is listening on port ${port}...`);
});

/******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/
