/******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/
 
const bGround = require('fcc-express-bground');
const myApp = require('./myApp');
const express = require('express');
const path = require('path'); // 1. 引入 path 模块
const app = express();

// 2. 配置 express.static 中间件来提供 public 目录下的静态文件
// 当请求路径以 /public 开头时，Express 会在项目根目录下的 'public' 文件夹中查找文件
// 例如：GET /public/style.css 会查找 __dirname/public/style.css
//app.use('/public', express.static(path.join(__dirname, 'public', 'style.css')));
console.log(__dirname+'/public/style.css');
app.use('/public', express.static(path.join(__dirname, 'public')));

if (!process.env.DISABLE_XORIGIN) {
  app.use((req, res, next) => {
    const allowedOrigins = ['https://narrow-plane.gomix.me', 'https://www.freecodecamp.com'];
    const origin = req.headers.origin || '*';
    if(!process.env.XORIG_RESTRICT || allowedOrigins.indexOf(origin) > -1){
         console.log(origin);
         res.setHeader('Access-Control-Allow-Origin', origin);
         res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    }
    next();
  });
}
/*app.get("/", (req, res)=>{
  console.log("Route / was hit!"); // Add this line

  // 使用 path.join 来构建路径更安全和跨平台
  const absolutePath = path.join(__dirname, 'views', 'index.html');
  //const absolutePath = path.join(__dirname, 'public', 'style.css');


    res.sendFile(absolutePath, (err) => {
    if (err) {
      console.error("Error sending file:", err);
      // 确保在发生错误时发送状态码
      res.status(err.status || 500).send('Internal Server Error');
    } else {
      console.log('File sent successfully!');
    }
  });
});*/

const port = process.env.PORT || 3000;
bGround.setupBackgroundApp(app, myApp, __dirname).listen(port, () => {
  bGround.log(`Node is listening on port ${port}...`);
});



/******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

